### ISSUE TITLE
Is this module usable in Drupal 8?

### ISSUE THREAD

**Issue by ebremer** [Islandora/openseadragon#2]
Is this module usable in Drupal 8?

**Comment by whikloj** [comment]
Yes, though I'm not sure how much testing has been done so your mileage may vary 😄 .

**Comment by ebremer** [comment]
I got some errors going into the configuration pages for the module,  (nothing of the page displayed) I'm using 8.4.2.
PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /www/drupal/modules/openseadragon/src/Config.php on line 70

This occurred in four places in the code.  For grins and giggles, I change the four places to:
bool $filterNull = NULL.  I can access the configuration page now, but I'm not entirely sure if my "fix" was even accurate.  My Drupal runs on CentOS 7.X with php56w.

Curious, in using the field formatter, what field type is used for a file upload and which type is used for a URL for iiif?

**Comment by whikloj** [comment]
@ebremer sorry this was built in Drupal 8.2 and I keep forgetting how fast they are moving. I'll try to update it to match the latest changes.

As for your other question, we get the URI [here](https://github.com/Islandora-CLAW/openseadragon/blob/8.x-1.x/src/File/FileInformation.php#L74) from the file on the filesystem. So this might not work as a formatter for a URI to an alternate IIIF server...that is a good point though never thought of that.

**Comment by ebremer** [comment]
So, in your set-up, is your Drupal and iiif server on the same system?

**Comment by whikloj** [comment]
Yes, currently we are using Cantaloupe running locally for development purposes. You can see the entire system here https://github.com/Islandora-Devops/claw-playbook

**Comment by ebremer** [comment]
So you use Drupal as the image uploader and display engine (using OSD) and Cantaloupe as the image tiling engine (iiif)?

**Comment by whikloj** [comment]
I think that is correct, but I'll be honest I'm fairly new to this.

That being said I can see your use case and how you could alter this to check the field type.

This field formatter is only meant for [image and file](https://github.com/Islandora-CLAW/openseadragon/blob/8.x-1.x/src/Plugin/Field/FieldFormatter/OpenSeadragonImageFormatter.php#L19-L20) types and I don't think you would have a Url in an image field.

So we would need to expand it to cover a [Url field](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Url.php/class/Url/8.4.x).

**Comment by ebremer** [comment]
I am working with gigapixel images.  The URI would be for an image on a iiif-type server, in my case, IIP.  Having the ability to include local and remote images would be very handy.

**Comment by ebremer** [comment]
We use OpenSeadragon now to access remote images via iiif protocol, but dropping OpenSeadragon into the context of Drupal would have many benefits which is what brought me to your module in the first place.

**Comment by whikloj** [comment]
Cool, I'll see if I can dedicate some time to that. No guarantees in the short term, but if I get something working I'll ping you to test it out.

**Comment by rosiel** [comment]
To answer this question (several years later) we now provide a block that takes (when placed) an IIIF manifest. For our uses, we often provide it `node/[node:nid]/manifest` which we set up to be that node's children, using an IIIF view formatter. But if you drop an external manifest URL into the block, it works - sometimes. 

Here's an example of it working with the manifest at https://digital.library.villanova.edu/Item/vudl:92879/Manifest

<img width="1024" alt="Screen Shot 2022-07-20 at 1 35 06 PM" src="https://user-images.githubusercontent.com/1943338/180036882-073ef7b5-e308-4990-869a-f6806ec65ed1.png">

However some other manifests manifestly don't work. For example, https://iiif.europeana.eu/presentation/9200396/BibliographicResource_3000118436165/manifest yeilds "Unable to load TileSource". 

I can not figure out how to set this up to debug javascript to figure out why that manifest doesn't work.
